/*
Copyright © 2021-2026  TokiNoBug
    This file is part of SlopeCraft.

    SlopeCraft is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    SlopeCraft is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SlopeCraft. If not, see <https://www.gnu.org/licenses/>.

    Contact with me:
    github:https://github.com/SlopeCraft/SlopeCraft
*/

#include <memory>
#include <format>
#include <print>
#include <cassert>
#include <ranges>
#include <iostream>

#include <QImage>
#include <QCoreApplication>
#include <magic_enum/magic_enum.hpp>

#include "BlockListManager/BlockListManager.h"
#include "sccl_internal.h"

bool inputs::need_build() const noexcept {
  if (litematica_option) {
    return true;
  }
  if (structure_option) {
    return true;
  }
  if (WESchem_option) {
    return true;
  }
  if (flat_diagram_option) {
    return true;
  }
  return false;
}

void canonicalize(inputs& task) {
  const size_t n_tasks = task.images.size();

  auto canonicalize_vector = [&](std::vector<std::string>& dest,
                                 const std::string& default_value,
                                 std::string field_name) {
    if (dest.size() == n_tasks) return;

    if (dest.empty()) {
      dest.resize(n_tasks, default_value);
      return;
    }

    if (dest.size() == 1) {
      const std::string val = dest[0];
      dest.resize(n_tasks, val);
      return;
    }
    throw std::runtime_error{
      std::format("{} has {} values, doesn't match image count ({}). Empty and "
                  "single value is also supported.",
                  field_name, dest.size(), n_tasks)};
  };
  // litematica options
  if (task.litematica_option) {
    auto& lo = task.litematica_option.value();
    canonicalize_vector(lo.litematica_names, "Litematica generated by sccl",
                        "litematica_names");
    canonicalize_vector(lo.litematica_region_names, "Developed by TokiNoBug",
                        "litematica_region_names");
  }
  if (task.WESchem_option) {
    auto& WEo = task.WESchem_option.value();
    canonicalize_vector(
        WEo.WESchem_names,
        "WorldEdit schematic generated by sccl, developed by TokiNoBug",
        "WESchem_names");
  }

  if (task.flat_diagram_option.has_value() and
      task.map_type not_eq SCL_mapTypes::Flat) {
    throw std::runtime_error{
      std::format("Can not export flat diagram with non-flat maps.")};
  }

  if (task.map_type == SCL_mapTypes::FileOnly and task.need_build()) {
    throw std::runtime_error{
      std::format("FileOnly maps can't be exported as litematica, structure, "
                  "schematic or flat diagram")};
  }
  if ((task.preprocess.background bitand 0xFF000000) != 0xFF000000) {
    throw std::runtime_error{std::format(
        "Background color {:#x} is not fully opactic. Alpha must be 255",
        task.preprocess.background)};
  }
}

struct error_report {
  std::string log;
  size_t counter{0};
};

void run(const inputs& task, bool build_dir_mode) {
  using namespace SlopeCraft;
  error_report err{};
  ui_callbacks ui{};
  ui.wind = &err;
  ui.cb_report_error = [](void* wind, errorFlag flag, const char* msg) {
    auto log = reinterpret_cast<error_report*>(wind);
    std::format_to(std::back_inserter(log->log), "{}: {}\n",
                   magic_enum::enum_name(flag), msg);
    log->counter++;
  };

  const std::filesystem::path SC_default_blocks_dir =
#ifdef __linux__
      "../share/SlopeCraft/Blocks_SCL";
#else
      "./Blocks_SCL";
#endif
  const std::filesystem::path SCL_blocks_dir = std::filesystem::canonical(
      std::filesystem::path{
        QCoreApplication::applicationDirPath().toStdString()} /
      (build_dir_mode ? "../SCL_block_lists" : SC_default_blocks_dir));
  // load block lists from zips
  const auto block_lists = [&] {
    std::vector<std::unique_ptr<block_list_interface, deleter>> ret;
    std::vector zips{
      SCL_blocks_dir / "FixedBlocks.zip",
      SCL_blocks_dir / "CustomBlocks.zip",
    };
    zips.append_range(task.extra_block_lists);
    for (const auto& path : zips) {
      std::string warnings, errors;
      warnings.resize(8192);
      errors.resize(8192);
      string_deliver sd_warnings{warnings.data(), warnings.size()},
          sd_errors{errors.data(), errors.size()};
      block_list_create_info blci;
      blci.warnings = &sd_warnings;
      blci.error = &sd_errors;
      std::unique_ptr<block_list_interface, deleter> ptr{
        SCL_create_block_list(path.string().c_str(), blci)};
      warnings.resize(sd_warnings.size);
      errors.resize(sd_errors.size);
      if (not warnings.empty()) {
        std::println("Warnings when parsing block list {}: {}", path.string(),
                     warnings);
      }
      if (ptr == nullptr) {
        throw std::runtime_error{std::format(
            "Failed to parse block list {}: {}", path.string(), errors)};
      }
      ret.emplace_back(std::move(ptr));
    }
    return ret;
  }();
  // Arrange blocks from zips
  const auto total_blocks = [&block_lists, &task] {
    std::vector<std::vector<mc_block_interface*>> total_blocks{64};
    for (auto& blp : block_lists) {
      std::vector<mc_block_interface*> blocks;
      std::vector<uint8_t> basecolors;
      blocks.resize(blp->size(), nullptr);
      basecolors.resize(blp->size(), 0);
      const auto n_blocks [[maybe_unused]] =
          blp->get_blocks(blocks.data(), basecolors.data(), basecolors.size());
      assert(n_blocks == blocks.size());
      assert(n_blocks == basecolors.size());

      for (const auto [blkp, base_color] :
           std::views::zip(blocks, basecolors)) {
        if (task.version >= blkp->getVersion()) {
          total_blocks[base_color].emplace_back(blkp);
        }
      }
    }
    return total_blocks;
  }();
  // load preset
  const auto [preset_values] =
      load_preset(QString::fromStdString(task.preset_json.string()));

  auto color_table = [&] {
    color_table_create_info ctci{};
    ctci.map_type = task.map_type;
    ctci.mc_version = task.version;
    std::ranges::fill(ctci.blocks, nullptr);
    std::ranges::fill(ctci.basecolor_allow_LUT, false);
    for (size_t basecolor = 0; basecolor < 64; basecolor++) {
      if (total_blocks.size() <= basecolor or
          preset_values.size() <= basecolor) {
        continue;
      }
      const auto& candidates = total_blocks[basecolor];
      if (candidates.empty()) {
        std::println("Base color {} is disabled because no available block",
                     basecolor);
        continue;
      }
      if (task.disable_base_colors.contains(basecolor)) {
        std::println("Base color {} is disabled by command line parameters",
                     basecolor);
        continue;
      }
      const auto& expected_blk = preset_values[basecolor];
      if (not expected_blk.first) {  // The preset disabled this
        std::println("Base color {} is disabled due to preset", basecolor);
        continue;
      }

      bool found_matched_blocks = false;
      for (const auto blkp : candidates) {
        if (QString::fromUtf8(blkp->getId()) == expected_blk.second) {
          std::println("Selecting {} for base color {}", blkp->getId(),
                       basecolor);
          ctci.blocks[basecolor] = blkp;
          ctci.basecolor_allow_LUT[basecolor] = true;
          found_matched_blocks = true;
          break;
        }
      }
      if (found_matched_blocks) {
        continue;
      }
      // select most preferred block
      auto selected = candidates[0];
      std::println(
          "Selecting {} for base color {} instead of preset assigned {} "
          "(missing from block list, or not available in this version)",
          selected->getId(), basecolor, expected_blk.second.toStdString());
      ctci.blocks[basecolor] = selected;
      ctci.basecolor_allow_LUT[basecolor] = true;
    }

    std::unique_ptr<SlopeCraft::color_table, deleter> ptr{
      SCL_create_color_table(ctci)};
    return ptr;
  }();
  
  std::vector<std::unique_ptr<converted_image, deleter>> converted_images;
  for (const auto& [idx, img_path] : task.images | std::views::enumerate) {
    QImage img;
    if (not img.load(QString::fromStdString(img_path.string()))) {
      throw std::runtime_error{
        std::format("Failed to load image {}", img_path.string())};
    }
    img = img.convertToFormat(QImage::Format_ARGB32);
    // preprocess image
    SCL_preprocessImage(
        reinterpret_cast<uint32_t*>(img.scanLine(0)),
        img.height() * img.width(), task.preprocess.pure_transparent,
        task.preprocess.half_transparent, task.preprocess.background);

    const_image_reference raw_img_ref{
      .data = reinterpret_cast<const uint32_t*>(img.constScanLine(0)),
      .rows = static_cast<size_t>(img.size().height()),
      .cols = static_cast<size_t>(img.size().width()),
    };

    convert_option opt;
    opt.algo = task.algo;
    opt.dither = task.dither;
    opt.ui = ui;
    std::println("[{} / {}] Converting image {}", idx + 1, task.images.size(),
                 img_path.string());
    std::unique_ptr<converted_image, deleter> converted_img{
      color_table->convert_image(raw_img_ref, opt)};
    if (converted_img == nullptr) {
      throw std::runtime_error{
        std::format("Failed to convert image {} with following error(s): \n{}",
                    img_path.string(), err.log)};
    }
    converted_images.emplace_back(std::move(converted_img));
  }
  // export converted images, map data files and assembled maps
  {
    const size_t n_tasks = [&] {
      size_t sum = 0;
      if (task.converted_image_option) {
        sum += 1;
      }
      if (task.map_data_files_option) {
        sum += 1;
        if (task.map_data_files_option.value().assembled_option) {
          sum += 1;
        }
      }
      return sum * task.images.size();
    }();

    size_t task_counter = 1;
    int map_idx_counter =
        task.map_data_files_option.value_or(export_map_data_files_option{})
            .begin_index;
    for (const auto& [idx, pair] :
         std::views::zip(task.images, converted_images) |
             std::views::enumerate) {
      const auto& [raw_img_path, converted_img] = pair;
      if (task.converted_image_option) {
        QImage img{QSize{static_cast<int>(converted_img->cols()),
                         static_cast<int>(converted_img->rows())},
                   QImage::Format_ARGB32};
        const auto dest_img_path = task.export_prefix / raw_img_path.filename();
        std::println("[{} / {}] Saving converted image {}", task_counter++,
                     n_tasks, dest_img_path.string());
        converted_img->get_converted_image(
            reinterpret_cast<uint32_t*>(img.scanLine(0)));
        if (not img.save(QString::fromStdString(dest_img_path.string()))) {
          throw std::runtime_error{std::format(
              "Failed to save converted image {}", dest_img_path.string())};
        }
      }

      if (task.map_data_files_option) {
        const auto& mdfo = task.map_data_files_option.value();
        map_data_file_options opt{};
        opt.begin_index = map_idx_counter;
        const auto path_str = task.export_prefix.string();
        opt.folder_path = path_str.c_str();
        std::println("[{} / {}] Saving map data files for image {}",
                     task_counter++, n_tasks, raw_img_path.string());
        if (not converted_img->export_map_data(opt)) {
          throw std::runtime_error{
            std::format("Failed to export map data files for image {}",
                        raw_img_path.string())};
        }
        if (mdfo.assembled_option) {
          const auto& ao = mdfo.assembled_option.value();
          assembled_maps_options amo{};
          amo.frame_variant = ao.frame_glowing ? SCL_item_frame_variant::glowing
                                               : SCL_item_frame_variant::common;
          amo.map_facing = ao.map_facing;
          amo.mc_version = task.version;
          amo.after_1_20_5 = mdfo.version_greater_1_20_5;
          amo.fixed_frame = ao.frame_fixed;
          amo.invisible_frame = ao.frame_transparent;
          amo.begin_index = map_idx_counter;

          const auto filename =
              (task.export_prefix / raw_img_path.stem()).string() +
              "_assembled.litematic";
          litematic_options lo{};
          std::println("[{} / {}] Saving assembled maps litematica {}",
                       task_counter++, n_tasks, filename);
          if (not converted_img->export_assembled_maps_litematic(
                  filename.c_str(), amo, lo)) {
            throw std::runtime_error{
              std::format("Failed to export assembled maps for image {}",
                          raw_img_path.string())};
          }
        }
      }
      // increase map counter
      size_t map_rows, map_cols;
      SCL_get_map_count(converted_img->rows(), converted_img->cols(), map_rows,
                        map_cols);
      map_idx_counter += map_rows * map_cols;
    }
  }

  // export schematic
  {
    const auto n_tasks = [&] {
      size_t ret = 1;  // build 3d structure
      if (task.litematica_option) ret++;
      if (task.structure_option) ret++;
      if (task.WESchem_option) ret++;
      if (task.flat_diagram_option) ret++;

      return ret * task.images.size();
    }();
    if (not task.need_build()) {
      return;
    }
    size_t task_counter = 1;
    for (const auto& [idx, pair] :
         std::views::zip(task.images, converted_images) |
             std::views::enumerate) {
      auto& [raw_img_path, converted_img] = pair;
      build_options build_opt{};
      build_opt.max_allowed_height = task.max_allowed_height;
      build_opt.bridge_interval = task.glass_bridge_interval;
      build_opt.compress_method = [&] -> SCL_compressSettings {
        if (task.lossy_compression and task.lossless_compression)
          return SCL_compressSettings::Both;
        if (task.lossy_compression and not task.lossless_compression)
          return SCL_compressSettings::ForcedOnly;
        if (not task.lossy_compression and task.lossless_compression)
          return SCL_compressSettings::NaturalOnly;
        // not lossy, not lossless
        return SCL_compressSettings::noCompress;
      }();
      build_opt.glass_method = task.glass_bridge;
      build_opt.enderman_proof = task.enderman_proof;
      build_opt.fire_proof = task.fire_proof;
      build_opt.connect_mushrooms = task.connect_mushroom;
      build_opt.support_block_settings = task.support_block;
      build_opt.ui = ui;

      std::println("[{} / {}] Building 3D structure for {}", task_counter++,
                   n_tasks, raw_img_path.string());
      std::unique_ptr<structure_3D, deleter> structure{
        color_table->build(*converted_img, build_opt)};

      if (structure == nullptr) {
        throw std::runtime_error{
          std::format("Failed to build 3D structure for {} with following "
                      "error(s):\n{}",
                      raw_img_path.string(), err.log)};
      }

      if (task.litematica_option) {
        auto& lo = task.litematica_option.value();
        litematic_options sclo{};
        sclo.litename_utf8 = lo.litematica_names[idx].c_str();
        sclo.region_name_utf8 = lo.litematica_region_names[idx].c_str();
        sclo.ui = ui;
        auto filename =
            (task.export_prefix /
             raw_img_path.filename().replace_extension(".litematic"))
                .string();
        std::println("[{} / {}] Exporting {}", task_counter++, n_tasks,
                     filename);
        if (not structure->export_litematica(filename.c_str(), sclo)) {
          throw std::runtime_error{
            std::format("Failed to export {} with following error(s):\n{}",
                        filename, err.log)};
        }
      }

      if (task.structure_option) {
        auto so = task.structure_option.value();
        vanilla_structure_options vso{};
        vso.is_air_structure_void = so.structure_is_air_void;
        vso.ui = ui;

        auto filename = (task.export_prefix /
                         raw_img_path.filename().replace_extension(".nbt"))
                            .string();
        std::println("[{} / {}] Exporting {}", task_counter++, n_tasks,
                     filename);
        if (not structure->export_vanilla_structure(filename.c_str(), vso)) {
          throw std::runtime_error{
            std::format("Failed to export {} with following error(s):\n{}",
                        filename, err.log)};
        }
      }

      if (task.WESchem_option) {
        auto& weso = task.WESchem_option.value();
        const auto required_mods_ptr = [&] {
          std::vector<const char*> ret;
          for (auto& str : weso.WESchem_required_mods) {
            ret.emplace_back(str.c_str());
          }
          return ret;
        }();

        WE_schem_options so{};
        so.required_mods_name_utf8 = required_mods_ptr.data();
        so.num_required_mods = required_mods_ptr.size();
        so.ui = ui;

        auto filename = (task.export_prefix /
                         raw_img_path.filename().replace_extension(".schem"))
                            .string();
        std::println("[{} / {}] Exporting {}", task_counter++, n_tasks,
                     filename);
        if (not structure->export_WE_schem(filename.c_str(), so)) {
          throw std::runtime_error{
            std::format("Failed to export {} with following error(s):\n{}",
                        filename, err.log)};
        }
      }

      if (task.flat_diagram_option) {
        auto& efdo = task.flat_diagram_option.value();
        flag_diagram_options fdo{};
        fdo.split_line_row_margin = efdo.splitline_row_interval;
        fdo.split_line_col_margin = efdo.splitline_col_interval;
        fdo.ui = ui;

        auto filename =
            (task.export_prefix /
             std::format("{}_flat-diagram.png", raw_img_path.stem().string()))
                .string();
        std::println("[{} / {}] Exporting {}", task_counter++, n_tasks,
                     filename);
        if (not structure->export_flat_diagram(filename.c_str(), *color_table,
                                               fdo)) {
          throw std::runtime_error{
            std::format("Failed to export {} with following error(s):\n{}",
                        filename, err.log)};
        }
      }
    }
    // finished
  }
}
